package Tiles;

public enum Direction {
  VERTICAL,
  HORIZONTAL,
  TOP_RIGHT_CORNER,
  BOTTOM_RIGHT_CORNER,
  TOP_LEFT_CORNER,
  BOTTOM_LEFT_CORNER,
  VERTICAL_RIGHT_T_JUNCTION,
  VERTICAL_LEFT_T_JUNCTION,
  HORIZONTAL_TOP_T_JUNCTION,
  HORIZONTAL_BOTTOM_T_JUNCTION,
  INTERSECTION
}
